
SET(GUROBI_ROOT_DIR "$ENV{GUROBI_HOME}")


MESSAGE(STATUS "Searching gurobi in: ${GUROBI_ROOT_DIR}")

FIND_PATH(GRB_INCLUDE_DIR
  gurobi_c.h
  PATHS ${GUROBI_ROOT_DIR}/include
)
MESSAGE(STATUS "GUROBI: INCLUDE DIR FOUND ${GRB_INCLUDE_DIR}")
FIND_LIBRARY(GRB_LIBRARY
   gurobi30
  PATHS ${GUROBI_ROOT_DIR}/lib
)

IF (GRB_INCLUDE_DIR AND GRB_LIBRARY)
	SET(GUROBI_INCLUDE_DIRS ${GRB_INCLUDE_DIR})
	SET(GUROBI_LIBRARIES ${GRB_LIBRARY})
	SET(GRB_FOUND TRUE)
ENDIF (GRB_INCLUDE_DIR AND GRB_LIBRARY)


IF (GRB_FOUND)
	IF (NOT Gurobi_FIND_QUIETLY)
		MESSAGE(STATUS "Found Gurobi: ${GRB_LIBRARY}")
	ENDIF (NOT Gurobi_FIND_QUIETLY)
ELSE (GRB_FOUND)
	IF (Gurobi_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find Gurobi")
	ENDIF (Gurobi_FIND_REQUIRED)
ENDIF (GRB_FOUND)
