
SET(GUROBICPP_ROOT_DIR "$ENV{GUROBI_HOME}")


MESSAGE(STATUS "Searching gurobi in: ${GUROBICPP_ROOT_DIR}")

FIND_PATH(GUROBICPP_INCLUDE_DIR
  gurobi_c++.h
  PATHS ${GUROBICPP_ROOT_DIR}/include
)
MESSAGE(STATUS "GUROBICPP: INCLUDE DIR FOUND ${GUROBICPP_INCLUDE_DIR}")
FIND_LIBRARY(GUROBICPP_LIBRARY
   gurobi_c++
  PATHS ${GUROBICPP_ROOT_DIR}/lib
)
MESSAGE(STATUS "GUROBICPP: LIB DIR FOUND ${GUROBICPP_LIBRARY}")

IF (GUROBICPP_INCLUDE_DIR AND GUROBICPP_LIBRARY)
	SET(GUROBICPP_INCLUDE_DIRS ${GUROBICPP_INCLUDE_DIR})
	SET(GUROBICPP_LIBRARIES ${GUROBICPP_LIBRARY})
	SET(GUROBICPP_FOUND TRUE)
ENDIF (GUROBICPP_INCLUDE_DIR AND GUROBICPP_LIBRARY)


IF (GUROBICPP_FOUND)
	IF (NOT GurobiCPP_FIND_QUIETLY)
		MESSAGE(STATUS "Found Gurobi C++: ${GUROBICPP_LIBRARY}")
	ENDIF (NOT GurobiCPP_FIND_QUIETLY)
ELSE (GUROBICPP_FOUND)
	IF (GurobiCPP_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find Gurobi C++")
	ENDIF (GurobiCPP_FIND_REQUIRED)
ENDIF (GUROBICPP_FOUND)
