
SET(CPLEX_SYSTEM "x86-64_debian4.0_4.1")
SET(CPLEX_LIBFORMAT  "static_pic")

SET(CPLEX_ROOT_DIR "$ENV{CPLEX_HOME}")


MESSAGE(STATUS "Searching CPLEX in: ${CPLEX_ROOT_DIR}")

FIND_PATH(CPLEX_INCLUDE_DIR
  cplex.h
  PATHS ${CPLEX_ROOT_DIR}/include/ilcplex
)
MESSAGE(STATUS "CPLEX: INCLUDE DIR FOUND ${CPLEX_INCLUDE_DIR}")
FIND_LIBRARY(CPLEX_LIBRARY
   libcplex.a
  PATHS ${CPLEX_ROOT_DIR}/lib/${CPLEX_SYSTEM}/${CPLEX_LIBFORMAT}
)
MESSAGE(STATUS "CPLEX: LIB DIR FOUND ${CPLEX_LIBRARY}")

IF (CPLEX_INCLUDE_DIR AND CPLEX_LIBRARY)
	SET(CPLEX_INCLUDE_DIRS ${CPLEX_INCLUDE_DIR})
	SET(CPLEX_LIBRARIES ${CPLEX_LIBRARY})
	SET(CPLEX_FOUND TRUE)
ENDIF (CPLEX_INCLUDE_DIR AND CPLEX_LIBRARY)


IF (CPLEX_FOUND)
	IF (NOT CPLEX_FIND_QUIETLY)
		MESSAGE(STATUS "Found CPLEX C++: ${CPLEX_LIBRARY}")
	ENDIF (NOT CPLEX_FIND_QUIETLY)
ELSE (CPLEX_FOUND)
	IF (CPLEX_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find CPLEX")
	ENDIF (CPLEX_FIND_REQUIRED)
ENDIF (CPLEX_FOUND)
