

FIND_PATH(GALIB_INCLUDE_DIR
  ga.h
)
MESSAGE(STATUS "GALIB: INCLUDE DIR FOUND ${GALIB_INCLUDE_DIR}")
FIND_LIBRARY(GALIB_LIBRARY
   libga.a
)
MESSAGE(STATUS "GALIB: LIB DIR FOUND ${GALIB_LIBRARY}")

IF (GALIB_INCLUDE_DIR AND GALIB_LIBRARY)
	SET(GALIB_INCLUDE_DIRS ${GALIB_INCLUDE_DIR})
	SET(GALIB_LIBRARIES ${GALIB_LIBRARY})
	SET(GALIB_FOUND TRUE)
ENDIF (GALIB_INCLUDE_DIR AND GALIB_LIBRARY)


IF (GALIB_FOUND)
	IF (NOT GALIB_FIND_QUIETLY)
		MESSAGE(STATUS "Found GALIB C++: ${GALIB_LIBRARY}")
	ENDIF (NOT GALIB_FIND_QUIETLY)
ELSE (GALIB_FOUND)
	IF (GALIB_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find GALIB")
	ENDIF (GALIB_FIND_REQUIRED)
ENDIF (GALIB_FOUND)
